"""macOS firewall access through pf (the packet filter behind `pfctl`).

piewall owns one pf anchor, `com.apple/piewall`. The stock /etc/pf.conf already evaluates
every `com.apple/*` anchor, so nothing outside piewall's own files is edited. The rules
piewall manages live in STATE_FILE (readable by everyone, so listing needs no password);
each change rewrites it, reloads the anchor and installs a LaunchDaemon that reloads it at
boot. Changes run as root through the standard macOS administrator password prompt.

pf filters packets, not programs: rules with a program or service are refused.
"""

from __future__ import annotations

import contextlib
import json
import os
import shlex
import subprocess
import tempfile
from dataclasses import replace
from pathlib import Path

from .backend import FirewallError
from .elevate import ElevationCancelled
from .model import Rule, is_any

ANCHOR = "com.apple/piewall"
STATE_DIR = Path("/Library/Application Support/piewall")
STATE_FILE = STATE_DIR / "rules.json"
PF_FILE = STATE_DIR / "pf.rules"
DAEMON_LABEL = "io.github.theeraphatstudent.piewall"
DAEMON_FILE = Path("/Library/LaunchDaemons") / f"{DAEMON_LABEL}.plist"

# pfctl -E takes a reference on pf so it stays on alongside other pf users (VPNs, Docker…).
_LOAD = f"/sbin/pfctl -q -E; /sbin/pfctl -q -a {ANCHOR} -f {shlex.quote(str(PF_FILE))}"
DAEMON_PLIST = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{DAEMON_LABEL}</string>
  <key>ProgramArguments</key>
  <array><string>/bin/sh</string><string>-c</string><string>{_LOAD}</string></array>
  <key>RunAtLoad</key><true/>
</dict>
</plist>
"""

_PROTO = {"tcp": "proto tcp", "udp": "proto udp", "icmpv4": "inet proto icmp",
          "icmpv6": "inet6 proto icmp6", "any": ""}


def _list(items: str) -> str:
    parts = [p.strip() for p in items.split(",") if p.strip()]
    return parts[0] if len(parts) == 1 else "{ " + " ".join(parts) + " }"


def _ports(ports: str) -> str:
    out = []
    for part in ports.split(","):
        lo, _, hi = part.strip().partition("-")
        if not lo.isdigit() or (hi and not hi.isdigit()):
            raise FirewallError(f"pf only takes numeric ports, not {part.strip()!r}")
        out.append(f"{lo}:{hi}" if hi else lo)
    return _list(",".join(out))


def render_rule(rule: Rule) -> str:
    """One Rule -> one pf rule line."""
    if rule.program or rule.service:
        raise FirewallError(f"'{rule.name}': macOS pf filters ports and addresses, "
                            f"not programs or services")
    proto = _PROTO.get(rule.protocol, f"proto {rule.protocol}")
    port = ""
    if not is_any(rule.local_ports):
        if rule.protocol == "any":
            proto = "proto { tcp udp }"  # pf ports need tcp or udp
        elif rule.protocol not in ("tcp", "udp"):
            raise FirewallError(f"'{rule.name}': ports need TCP or UDP")
        port = f" port {_ports(rule.local_ports)}"
    remote = "any" if is_any(rule.remote_addresses) else _list(rule.remote_addresses)
    if rule.direction == "in":
        ends = f"from {remote} to any{port}"
    else:
        ends = f"from any{port} to {remote}"
    verb = "pass" if rule.action == "allow" else "block"
    label = rule.name.replace('"', "'")[:63]  # pf labels hold 63 characters
    return " ".join(p for p in (verb, rule.direction, proto, ends, f'label "{label}"') if p)


def render(rules: list[Rule]) -> str:
    """The anchor's ruleset. pf lets the last match win, so Block rules go last: like
    Windows, Block beats Allow. Disabled rules are kept in STATE_FILE only."""
    on = [r for r in rules if r.enabled]
    lines = [render_rule(r) for r in on if r.action == "allow"]
    lines += [render_rule(r) for r in on if r.action != "allow"]
    return "# Generated by piewall; edit rules with piewall, not here.\n" + "".join(
        line + "\n" for line in lines)


def _run_as_root(script: str) -> None:
    if os.geteuid() == 0:
        cmd = ["/bin/sh", "-c", script]
    else:
        quoted = script.replace("\\", "\\\\").replace('"', '\\"')
        cmd = ["/usr/bin/osascript", "-e",
               f'do shell script "{quoted}" with prompt "piewall wants to change the firewall." '
               f"with administrator privileges"]
    done = subprocess.run(cmd, capture_output=True, text=True)
    if done.returncode == 0:
        return
    if "(-128)" in done.stderr:  # user pressed Cancel
        raise ElevationCancelled
    raise FirewallError(done.stderr.strip() or f"pfctl failed ({done.returncode})")


class PfBackend:
    def __init__(self, state_file: Path = STATE_FILE, run=_run_as_root) -> None:
        self.state_file = state_file
        self._run = run
        self._rules: list[Rule] = []
        self._depth = 0
        self._dirty = False

    def _load(self) -> list[Rule]:
        try:
            data = json.loads(self.state_file.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return []
        return [Rule.from_dict(d) for d in data["rules"]]

    def _current(self) -> list[Rule]:
        """Fresh from disk (another piewall may have changed it), except mid-batch."""
        if not self._depth:
            self._rules = self._load()
        return self._rules

    def list_rules(self) -> list[Rule]:
        return list(self._current())

    @contextlib.contextmanager
    def batch(self):
        """Several changes, one commit (one password prompt). Nothing is saved on error."""
        saved = list(self._current())
        self._depth += 1
        try:
            yield
            if self._depth == 1 and self._dirty:
                self._commit()
        except BaseException:
            self._rules = saved
            raise
        finally:
            self._depth -= 1
            if not self._depth:
                self._dirty = False

    def _changed(self, rules: list[Rule]) -> None:
        before, self._rules = self._rules, rules
        if self._depth:
            self._dirty = True
            return
        try:
            self._commit()
        except BaseException:
            self._rules = before
            raise

    def _commit(self) -> None:
        pf = render(self._rules)  # raises before anything is touched
        state = json.dumps({"version": 1, "rules": [r.to_dict() for r in self._rules]}, indent=2)
        with tempfile.TemporaryDirectory(prefix="piewall-") as tmp:
            files = {"rules.json": state, "pf.rules": pf, "daemon.plist": DAEMON_PLIST}
            for name, text in files.items():
                Path(tmp, name).write_text(text, encoding="utf-8")
            q = lambda p: shlex.quote(str(p))  # noqa: E731
            t = lambda name: q(Path(tmp, name))  # noqa: E731
            self._run(" && ".join([
                f"/sbin/pfctl -q -n -a {ANCHOR} -f {t('pf.rules')}",  # validate before replacing anything
                f"/bin/mkdir -p {q(self.state_file.parent)}",
                f"/usr/bin/install -m 644 {t('rules.json')} {q(self.state_file)}",
                f"/usr/bin/install -m 644 {t('pf.rules')} {q(PF_FILE)}",
                f"/usr/bin/install -m 644 {t('daemon.plist')} {q(DAEMON_FILE)}",
                f"({_LOAD})",
            ]))

    def add_rule(self, rule: Rule) -> None:
        render_rule(rule)  # refuse before prompting for a password
        self._changed([*self._current(), rule])

    def delete_rules(self, name: str) -> int:
        rules = self._current()
        kept = [r for r in rules if r.name != name]
        count = len(rules) - len(kept)
        if count:
            self._changed(kept)
        return count

    def _set(self, name: str, **changes) -> int:
        rules = self._current()
        count = sum(r.name == name for r in rules)
        if count:
            self._changed([replace(r, **changes) if r.name == name else r for r in rules])
        return count

    def set_enabled(self, name: str, enabled: bool) -> int:
        return self._set(name, enabled=enabled)

    def set_action(self, name: str, action: str) -> int:
        return self._set(name, action=action)
