# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for piewall.

Builds two executables from the same code:
  piewall.exe      windowed GUI  (piewall.gui:main)
  piewall-cli.exe  console CLI   (piewall.cli:main)

PIEWALL_MODE picks the layout (packaging/build.ps1 runs both):
  onedir   (default) both exes share one _internal folder; used by the installer.
  onefile  each exe is self-contained; the portable release assets.

Run from the repo root:
  $env:PIEWALL_MODE = "onedir"
  uv run pyinstaller packaging/piewall.spec --noconfirm --clean
"""

import os
import re
import tomllib
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files

MODE = os.environ.get("PIEWALL_MODE", "onedir").lower()
if MODE not in ("onedir", "onefile"):
    raise SystemExit(f"PIEWALL_MODE must be onedir or onefile, got {MODE!r}")

HERE = Path(SPECPATH)  # noqa: F821 (injected by PyInstaller)
ROOT = HERE.parent
SRC = ROOT / "src"
ICON = str(SRC / "piewall" / "assets" / "piewall.ico")
MANIFEST = str(HERE / "piewall.manifest")

# ---- version resource, generated from pyproject.toml ------------------------------------------
VERSION = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
_nums = [int(n) for n in re.findall(r"\d+", VERSION.split("+")[0])[:4]]
VERSION_TUPLE = tuple((_nums + [0, 0, 0, 0])[:4])


def version_file(internal_name: str, exe_name: str, description: str) -> str:
    text = f"""# Generated by packaging/piewall.spec from pyproject.toml; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={VERSION_TUPLE}, prodvers={VERSION_TUPLE},
                    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Theeraphat'),
      StringStruct('FileDescription', {description!r}),
      StringStruct('FileVersion', {VERSION!r}),
      StringStruct('InternalName', {internal_name!r}),
      StringStruct('LegalCopyright', '\\u00a9 2026 Theeraphat'),
      StringStruct('OriginalFilename', {exe_name!r}),
      StringStruct('ProductName', 'piewall'),
      StringStruct('ProductVersion', {VERSION!r})])]),
    VarFileInfo([VarStruct('Translation', [0x0409, 1200])])
  ]
)
"""
    path = Path(workpath) / f"version-{internal_name}.txt"  # noqa: F821 (injected)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return str(path)


# ---- analysis ---------------------------------------------------------------------------------
DATAS = [
    (str(SRC / "piewall" / "assets"), "piewall/assets"),  # icons read via importlib.resources
    *collect_data_files("sv_ttk"),  # Sun Valley theme .tcl + images
]
# Imported lazily (inside functions or by gui.py as it evolves); list them so they are always bundled.
HIDDEN = ["sv_ttk", "darkdetect", "win32com.client.dynamic", "win32com.shell.shell"]
EXCLUDES = [
    "pytest", "_pytest", "pip", "setuptools", "pkg_resources", "distutils", "ensurepip", "venv",
    "lib2to3", "idlelib", "pydoc_data", "turtle", "turtledemo", "test", "tkinter.test",
    "sqlite3", "xmlrpc", "curses", "doctest", "pdb", "unittest",
    "win32ui", "pythonwin", "win32com.demos", "win32com.test", "win32comext.axscript",
    "numpy", "PIL",
    # Optional C accelerators with pure-Python / builtin fallbacks (libcrypto alone is ~8 MB).
    "_hashlib", "_ssl", "ssl", "_decimal", "_bz2", "_lzma",
]
# Tcl/Tk data piewall never uses: time zones (clock) and message catalogs (Windows dialogs are native).
DROP_DATA = ("_tcl_data/tzdata/", "_tcl_data/msgs/", "_tk_data/msgs/")


def analysis(script: str):
    a = Analysis(  # noqa: F821
        [str(HERE / script)],
        pathex=[str(SRC)],
        datas=DATAS,
        hiddenimports=HIDDEN,
        excludes=EXCLUDES,
        noarchive=False,
        optimize=1,  # strip asserts; keep docstrings
    )
    a.datas = [d for d in a.datas if not d[0].replace("\\", "/").startswith(DROP_DATA)]
    return a


gui_a = analysis("piewall_gui.py")
cli_a = analysis("piewall_cli.py")


def exe(a, name: str, *, console: bool, description: str):
    common = dict(
        name=name,
        icon=ICON,
        manifest=MANIFEST,
        version=version_file(name, f"{name}.exe", description),
        console=console,
        disable_windowed_traceback=False,
        debug=False,
        strip=False,
        upx=False,  # UPX-packed binaries are a classic AV false-positive trigger
        target_arch=None,
    )
    pyz = PYZ(a.pure)  # noqa: F821
    if MODE == "onefile":
        return EXE(pyz, a.scripts, a.binaries, a.datas, [], runtime_tmpdir=None, **common)  # noqa: F821
    return EXE(pyz, a.scripts, [], exclude_binaries=True, **common)  # noqa: F821


gui_exe = exe(gui_a, "piewall", console=False, description="piewall - Windows Firewall rules")
cli_exe = exe(cli_a, "piewall-cli", console=True,
              description="piewall command line - Windows Firewall rules")

if MODE == "onedir":
    COLLECT(  # noqa: F821
        gui_exe, gui_a.binaries, gui_a.datas,
        cli_exe, cli_a.binaries, cli_a.datas,
        strip=False,
        upx=False,
        name="piewall",
    )
